### ISSUE TITLE
您好~关于第一段假段落首行缩进会导致垂直距离变化的问题，想跟您请教下~

### ISSUE THREAD

**Issue by Rsweater** [tzhTaylor/typst-sjtu-thesis-master#1]
大佬，您好~

目前，在制作模板过程中遇见了第一段首行缩进的问题。目前，看到常用的方法是[社区总结的方法](https://typst-doc-cn.github.io/guide/FAQ/first-line-indent.html)假段落或者直接`#h(2em)`。

但是，假段落想要实现第一段文字首行缩进，目前看到其他论文模板里面都是在标题后加假段落，但是那样会引起标题的垂直距离变化；只能在每段使用`#h(2em)`的方式。在寻求直接修改段落的方法。
![录屏_20241126_122710](https://github.com/user-attachments/assets/e04ef5f8-2e8c-412b-873b-c162c6adf16d)

随后，看到了您的repo，挺奇妙~没有在标题设置的位置使用假段落，没有直接在文本中使用`#h(2em)`，也没有发现第三方库，似乎只有列表之类的使用了假段落，但是看您的实现了第一段的首行缩进。想要请教下，您是怎么实现？

**Comment by tzhTaylor** [comment]
我也是看到你的issue之后，才发现这个事情，哈哈哈～
<img width="875" alt="SCR-20241129-kgsl" src="https://github.com/user-attachments/assets/20b4dd73-32fd-4574-afbd-b416b768d55f">
我也试验了一下，实际上是`show heading: it => {it.body}`起的作用，我也不懂这个原理是啥😳，我也在学习的过程中，可能就是在自定义标题的过程中误打误撞吧，我平时写报告也都是fakepar来着。
至于标题的垂直距离的话，因为我这里本身就是在自定义标题的格式嘛，所以这个垂直距离就是一起在调。
虽然我的回答没啥技术含量，但希望能帮到你，也感谢你看得这么细致。

**Comment by Rsweater** [comment]
感谢感谢~  
学到了~ 
祝好！
